In [1]:
!ls

A3SS
A5SS
common_between_comparisons.ipynb
common_NOT-SIG-splicing_events.txt
common_SIG-splicing_events.txt
De_novo_comparison-events-JC.ipynb
De_novo_merge-events-bAmy_VS_CTR.ipynb
De_novo_merge-events-CBNR20-bAmy-vs-bAmy.ipynb
De_novo_merge-NOT-SIG-events-bAmy_VS_CTR.ipynb
De_novo_merge-NOT-SIG-events-CBNR20-bAmy-vs-bAmy.ipynb
DE_novo_NOT-SIG-splicing_events_bAmy_VS_CTR.txt
DE_novo_NOT-SIG-splicing_events_CBNR20_bAmy-vs-bAmy.txt
DE_novo_splicing_events_bAmy_VS_CTR.txt
DE_novo_splicing_events_CBNR20-bAmy_vs_bAmy.txt
Figure1_annotated-and-denovo.ipynb
MXE
NOT-SIG-splicing_events_bAmy_VS_CTR.txt
NOT-SIG-splicing_events_CBNR20-bAmy-vs-bAmy.txt
retain_only_denovo_events_bAmy_VS_CTR.ipynb
retain_only_denovo_events_bAmy_VS_CTR-NOT-SIG.ipynb
retain_only_denovo_events_CBNR20-bAmy_vs_bAmy.ipynb
retain_only_denovo_events_CBNR20-bAmy_vs_bAmy-NOT-SIG.ipynb
RI
SE
splicing_events_bAmy_VS_CTR.txt
splicing_events_CBNR20-bAmy-vs-bAmy.txt

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_denovo=pd.read_csv('DE_novo_NOT-SIG-splicing_events_CBNR20_bAmy-vs-bAmy.txt',sep='\t')

In [4]:
# Convert 'coho7' and 'coho8' to integers, handling NaN values
df_denovo['coho7'] = df_denovo['coho7'].fillna(0).astype(int)  # Fill NaN with 0 and convert to int
df_denovo['coho8'] = df_denovo['coho8'].fillna(0).astype(int)  # Fill NaN with 0 and convert to int

In [5]:
df_denovo

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference
0,MXE,ENSG00000291050,TEKT4P2,chr21,-,9077485,9077714,9124361,9124421,9070213,9070444,9127488,9127547,1.000000,"0.0,NA","0.0,0.587",-0.293
1,MXE,ENSG00000215386,MIR99AHG,chr21,+,16231055,16231115,16391613,16391685,16181590,16181687,16487489,16488336,1.000000,"0.0,NA","1.0,1.0",-1.000
2,MXE,ENSG00000182670,TTC3,chr21,+,37157160,37157214,37158130,37158203,37156654,37156906,37159698,37159745,0.186027,"0.686,1.0","0.0,0.908",0.389
3,MXE,ENSG00000159131,GART,chr21,-,33505973,33506104,33509782,33509920,33505560,33505702,33511251,33511458,0.316291,"0.872,0.577","0.934,0.883",-0.184
4,MXE,ENSG00000142168,SOD1,chr21,+,31663789,31663886,31666448,31666518,31659692,31659841,31667257,31667375,0.869814,"0.245,0.289","0.279,0.318",-0.031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55712,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710353,111709525,111709684,111715820,111715962,0,0,1.000000,"1.0,0.244","0.617,NA",0.005
55713,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710437,111709525,111709684,111715820,111715962,0,0,0.142072,"1.0,0.0","0.429,1.0",-0.215
55714,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,0,0,1.000000,"1.0,0.667","0.429,1.0",0.119
55715,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111866155,111866231,111870270,111870360,0,0,1.000000,"1.0,NA","1.0,0.576",0.212
55716,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111867571,111867669,111870270,111870360,0,0,0.511650,"0.665,0.759","0.944,0.833",-0.176

In [6]:
coho=list(df_denovo.columns[1:13])
# Collapse only the specified columns in 'coho' into a single string
df_denovo['collapsed'] = df_denovo[coho].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
# Strip ' nan' from the 'collapsed' column
# Strip ' nan' only at the end of the string in the 'collapsed' column
# Strip multiple occurrences of ' nan' at the end of the string in the 'collapsed' column
df_denovo['collapsed'] = df_denovo['collapsed'].str.replace(r'(\s?0)+$', '', regex=True)

In [7]:
df_denovo['DE-NOVO']=False

In [8]:
df_denovo.at[489,'collapsed']

'ENSG00000132964 CDK8 chr13 + 26393366 26393510 26396284 26396354 26385210 26385342 26397152 26397225'

In [9]:
#for classe in df_denovo['Class'].unique():
#    novel_path='15_10_2024_DENOVO-output_rMATS_bAmy-vs-CTR/fromGTF.novelSpliceSite.%s.txt'%(classe)
#    Ndf=pd.read_csv(novel_path,sep='\t',index_col='ID')
#    Ndf['collapsed'] = Ndf.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
#    for el in Ndf['collapsed']:
#        for i in df_denovo.index:
#            if df_denovo.at[i,'collapsed']==el:
#                df_denovo.at[i,'DE-NOVO']=True

In [10]:
# Assuming df_denovo is already loaded
for classe in df_denovo['Class'].unique():
    novel_path = f'../24_09_2024_DENOVO-output_rMATS_CBNR20-bAmy-vs-bAmy/fromGTF.novelSpliceSite.{classe}.txt'
    
    # Read the CSV into a DataFrame
    Ndf = pd.read_csv(novel_path, sep='\t', index_col='ID')
    
    # Collapse values of relevant columns into a single string (use specific columns if needed)
    Ndf['collapsed'] = Ndf.astype(str).agg(' '.join, axis=1)
    
    # Use pd.Series.isin() to check for matching collapsed strings
    matched_indices = df_denovo[df_denovo['collapsed'].isin(Ndf['collapsed'])].index
    
    # Set the 'DE-NOVO' column to True for all matching rows
    df_denovo.loc[matched_indices, 'DE-NOVO'] = True

In [11]:
df_denovo=df_denovo.drop(columns=['collapsed'])
df_denovo[['coho7', 'coho8']] = df_denovo[['coho7', 'coho8']].replace(0, np.nan)
df_denovo.to_csv('NOT-SIG-splicing_events_CBNR20-bAmy-vs-bAmy.txt',sep='\t',index=False)

In [12]:
df_denovo

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference,DE-NOVO
0,MXE,ENSG00000291050,TEKT4P2,chr21,-,9077485,9077714,9124361,9124421,9070213,9070444,9127488.0,9127547.0,1.000000,"0.0,NA","0.0,0.587",-0.293,False
1,MXE,ENSG00000215386,MIR99AHG,chr21,+,16231055,16231115,16391613,16391685,16181590,16181687,16487489.0,16488336.0,1.000000,"0.0,NA","1.0,1.0",-1.000,False
2,MXE,ENSG00000182670,TTC3,chr21,+,37157160,37157214,37158130,37158203,37156654,37156906,37159698.0,37159745.0,0.186027,"0.686,1.0","0.0,0.908",0.389,False
3,MXE,ENSG00000159131,GART,chr21,-,33505973,33506104,33509782,33509920,33505560,33505702,33511251.0,33511458.0,0.316291,"0.872,0.577","0.934,0.883",-0.184,False
4,MXE,ENSG00000142168,SOD1,chr21,+,31663789,31663886,31666448,31666518,31659692,31659841,31667257.0,31667375.0,0.869814,"0.245,0.289","0.279,0.318",-0.031,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55712,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710353,111709525,111709684,111715820,111715962,NaN,NaN,1.000000,"1.0,0.244","0.617,NA",0.005,True
55713,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710437,111709525,111709684,111715820,111715962,NaN,NaN,0.142072,"1.0,0.0","0.429,1.0",-0.215,True
55714,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,NaN,NaN,1.000000,"1.0,0.667","0.429,1.0",0.119,True
55715,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111866155,111866231,111870270,111870360,NaN,NaN,1.000000,"1.0,NA","1.0,0.576",0.212,False
55716,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111867571,111867669,111870270,111870360,NaN,NaN,0.511650,"0.665,0.759","0.944,0.833",-0.176,False

In [13]:
df_denovo[df_denovo['DE-NOVO']]

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference,DE-NOVO
2900,MXE,ENSG00000160191,PDE9A,chr21,+,42700631,42700674,42731769,42731949,42698967,42699011,42732069.0,42732124.0,1.000000,"1.0,0.0","0.0,0.0",0.500,True
2902,MXE,ENSG00000198089,SFI1,chr22,+,31577175,31577223,31578381,31578452,31575230,31575392,31580271.0,31580364.0,1.000000,"0.092,0.0","0.0,0.0",0.046,True
2903,MXE,ENSG00000198089,SFI1,chr22,+,31602606,31602785,31606327,31606394,31602211,31602293,31607936.0,31608033.0,1.000000,"0.911,1.0","1.0,1.0",-0.044,True
2904,MXE,ENSG00000138942,RNF185,chr22,+,31176257,31176417,31187046,31187270,31160242,31160303,31192683.0,31192702.0,1.000000,"0.0,0.0","0.0,0.167",-0.084,True
2905,MXE,ENSG00000228315,GUSBP11,chr22,-,23695172,23695517,23700725,23700831,23683724,23683867,23705428.0,23705541.0,1.000000,"0.0,NA","0.0,0.368",-0.184,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55710,SE,ENSG00000139624,CERS5,chr12,-,50133932,50134068,50130412,50130694,50134545,50134702,NaN,NaN,1.000000,"0.312,0.115","0.155,0.153",0.059,True
55711,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710353,111709525,111709684,111712497,111712657,NaN,NaN,0.452568,"0.244,0.0","0.659,0.047",-0.231,True
55712,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710353,111709525,111709684,111715820,111715962,NaN,NaN,1.000000,"1.0,0.244","0.617,NA",0.005,True
55713,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710437,111709525,111709684,111715820,111715962,NaN,NaN,0.142072,"1.0,0.0","0.429,1.0",-0.215,True
55714,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,NaN,NaN,1.000000,"1.0,0.667","0.429,1.0",0.119,True