In [1]:
!ls

A3SS
A5SS
common_between_comparisons.ipynb
common_NOT-SIG-splicing_events.txt
common_SIG-splicing_events.txt
De_novo_comparison-events-JC.ipynb
De_novo_merge-events-bAmy_VS_CTR.ipynb
De_novo_merge-events-CBNR20-bAmy-vs-bAmy.ipynb
De_novo_merge-NOT-SIG-events-bAmy_VS_CTR.ipynb
De_novo_merge-NOT-SIG-events-CBNR20-bAmy-vs-bAmy.ipynb
DE_novo_NOT-SIG-splicing_events_bAmy_VS_CTR.txt
DE_novo_NOT-SIG-splicing_events_CBNR20_bAmy-vs-bAmy.txt
DE_novo_splicing_events_bAmy_VS_CTR.txt
DE_novo_splicing_events_CBNR20-bAmy_vs_bAmy.txt
Figure1_annotated-and-denovo.ipynb
MXE
NOT-SIG-splicing_events_bAmy_VS_CTR.txt
NOT-SIG-splicing_events_CBNR20-bAmy-vs-bAmy.txt
retain_only_denovo_events_bAmy_VS_CTR.ipynb
retain_only_denovo_events_bAmy_VS_CTR-NOT-SIG.ipynb
retain_only_denovo_events_CBNR20-bAmy_vs_bAmy.ipynb
retain_only_denovo_events_CBNR20-bAmy_vs_bAmy-NOT-SIG.ipynb
RI
SE
splicing_events_bAmy_VS_CTR.txt
splicing_events_CBNR20-bAmy-vs-bAmy.txt

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_denovo=pd.read_csv('DE_novo_NOT-SIG-splicing_events_bAmy_VS_CTR.txt',sep='\t')

In [4]:
# Convert 'coho7' and 'coho8' to integers, handling NaN values
df_denovo['coho7'] = df_denovo['coho7'].fillna(0).astype(int)  # Fill NaN with 0 and convert to int
df_denovo['coho8'] = df_denovo['coho8'].fillna(0).astype(int)  # Fill NaN with 0 and convert to int

In [5]:
df_denovo

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference
0,MXE,ENSG00000182670,TTC3,chr21,+,37157160,37157214,37158130,37158203,37156654,37156906,37159698,37159745,1.000000,"0.0,0.908","0.422,0.814",-0.164
1,MXE,ENSG00000159131,GART,chr21,-,33505973,33506104,33509782,33509920,33505560,33505702,33511251,33511458,0.148391,"0.934,0.883","0.8,0.749",0.134
2,MXE,ENSG00000159267,HLCS,chr21,-,36946008,36946154,36947332,36948287,36938831,36938994,36962035,36962170,1.000000,"0.499,1.0","1.0,0.0",0.250
3,MXE,ENSG00000159267,HLCS,chr21,-,36946008,36946154,36948165,36948287,36938831,36938994,36962035,36962170,1.000000,"0.685,1.0","NA,0.0",0.843
4,MXE,ENSG00000183570,PCBP3,chr21,+,45913950,45914025,45917587,45917629,45910901,45911030,45929916,45929995,1.000000,"0.061,0.203","0.051,0.299",-0.043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60530,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,0,0,1.000000,"0.429,1.0","1.0,1.0",-0.285
60531,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710437,111715820,111715962,0,0,1.000000,"1.0,0.846","1.0,1.0",-0.077
60532,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111866155,111866231,111870270,111870360,0,0,1.000000,"1.0,0.576","0.52,NA",0.268
60533,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111867571,111867669,111870270,111870360,0,0,0.302125,"0.944,0.833","0.809,0.53",0.219
60534,SE,ENSG00000089022,MAPKAPK5,chr12,+,111870274,111870360,111867571,111867669,111871084,111871180,0,0,1.000000,"0.88,0.921","0.808,1.0",-0.003

In [6]:
coho=list(df_denovo.columns[1:13])
# Collapse only the specified columns in 'coho' into a single string
df_denovo['collapsed'] = df_denovo[coho].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
# Strip ' nan' from the 'collapsed' column
# Strip ' nan' only at the end of the string in the 'collapsed' column
# Strip multiple occurrences of ' nan' at the end of the string in the 'collapsed' column
df_denovo['collapsed'] = df_denovo['collapsed'].str.replace(r'(\s?0)+$', '', regex=True)

In [7]:
df_denovo['DE-NOVO']=False

In [8]:
df_denovo.at[489,'collapsed']

'ENSG00000137764 MAP2K5 chr15 + 67550033 67550082 67563282 67563350 67542702 67543470 67580753 67580823'

In [9]:
#for classe in df_denovo['Class'].unique():
#    novel_path='15_10_2024_DENOVO-output_rMATS_bAmy-vs-CTR/fromGTF.novelSpliceSite.%s.txt'%(classe)
#    Ndf=pd.read_csv(novel_path,sep='\t',index_col='ID')
#    Ndf['collapsed'] = Ndf.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
#    for el in Ndf['collapsed']:
#        for i in df_denovo.index:
#            if df_denovo.at[i,'collapsed']==el:
#                df_denovo.at[i,'DE-NOVO']=True

In [10]:
# Assuming df_denovo is already loaded
for classe in df_denovo['Class'].unique():
    novel_path = f'../24_09_2024_DENOVO-output_rMATS_bAmy-vs-CTR/fromGTF.novelSpliceSite.{classe}.txt'
    
    # Read the CSV into a DataFrame
    Ndf = pd.read_csv(novel_path, sep='\t', index_col='ID')
    
    # Collapse values of relevant columns into a single string (use specific columns if needed)
    Ndf['collapsed'] = Ndf.astype(str).agg(' '.join, axis=1)
    
    # Use pd.Series.isin() to check for matching collapsed strings
    matched_indices = df_denovo[df_denovo['collapsed'].isin(Ndf['collapsed'])].index
    
    # Set the 'DE-NOVO' column to True for all matching rows
    df_denovo.loc[matched_indices, 'DE-NOVO'] = True

In [11]:
df_denovo=df_denovo.drop(columns=['collapsed'])
df_denovo[['coho7', 'coho8']] = df_denovo[['coho7', 'coho8']].replace(0, np.nan)
df_denovo.to_csv('NOT-SIG-splicing_events_bAmy_VS_CTR.txt',sep='\t',index=False)

In [12]:
df_denovo

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference,DE-NOVO
0,MXE,ENSG00000182670,TTC3,chr21,+,37157160,37157214,37158130,37158203,37156654,37156906,37159698.0,37159745.0,1.000000,"0.0,0.908","0.422,0.814",-0.164,False
1,MXE,ENSG00000159131,GART,chr21,-,33505973,33506104,33509782,33509920,33505560,33505702,33511251.0,33511458.0,0.148391,"0.934,0.883","0.8,0.749",0.134,False
2,MXE,ENSG00000159267,HLCS,chr21,-,36946008,36946154,36947332,36948287,36938831,36938994,36962035.0,36962170.0,1.000000,"0.499,1.0","1.0,0.0",0.250,False
3,MXE,ENSG00000159267,HLCS,chr21,-,36946008,36946154,36948165,36948287,36938831,36938994,36962035.0,36962170.0,1.000000,"0.685,1.0","NA,0.0",0.843,False
4,MXE,ENSG00000183570,PCBP3,chr21,+,45913950,45914025,45917587,45917629,45910901,45911030,45929916.0,45929995.0,1.000000,"0.061,0.203","0.051,0.299",-0.043,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60530,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,NaN,NaN,1.000000,"0.429,1.0","1.0,1.0",-0.285,True
60531,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710437,111715820,111715962,NaN,NaN,1.000000,"1.0,0.846","1.0,1.0",-0.077,True
60532,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111866155,111866231,111870270,111870360,NaN,NaN,1.000000,"1.0,0.576","0.52,NA",0.268,False
60533,SE,ENSG00000089022,MAPKAPK5,chr12,+,111868752,111868876,111867571,111867669,111870270,111870360,NaN,NaN,0.302125,"0.944,0.833","0.809,0.53",0.219,False
60534,SE,ENSG00000089022,MAPKAPK5,chr12,+,111870274,111870360,111867571,111867669,111871084,111871180,NaN,NaN,1.000000,"0.88,0.921","0.808,1.0",-0.003,False

In [13]:
df_denovo[df_denovo['DE-NOVO']]

,Class,GeneID,geneSymbol,chr,strand,coho1,coho2,coho3,coho4,coho5,coho6,coho7,coho8,FDR,IncLevel1,IncLevel2,IncLevelDifference,DE-NOVO
3234,MXE,ENSG00000160191,PDE9A,chr21,+,42731769,42731949,42732071,42732124,42698967,42699011,42733355.0,42733426.0,1.000000,"0.476,0.089","0.254,0.185",0.063,True
3235,MXE,ENSG00000138942,RNF185,chr22,+,31176257,31176417,31187046,31187270,31160242,31160303,31192683.0,31192702.0,1.000000,"0.0,0.167","0.0,0.0",0.084,True
3236,MXE,ENSG00000228315,GUSBP11,chr22,-,23695172,23695517,23700725,23700831,23683724,23683867,23705428.0,23705541.0,1.000000,"0.0,0.368","0.0,0.0",0.184,True
3238,MXE,ENSG00000188130,MAPK12,chr22,-,50249102,50249168,50249327,50249516,50248830,50248890,50249634.0,50249703.0,1.000000,"0.0,0.108","0.0,0.266",-0.079,True
3239,MXE,ENSG00000188130,MAPK12,chr22,-,50257360,50257660,50257903,50257945,50257081,50257193,50258242.0,50258301.0,1.000000,"NA,1.0","0.0,0.509",0.746,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60527,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710353,111709525,111709684,111715820,111715962,NaN,NaN,1.000000,"0.617,NA","0.392,0.0",0.421,True
60528,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710437,111709525,111709684,111712497,111712657,NaN,NaN,1.000000,"0.6,0.071","0.176,0.333",0.081,True
60529,SE,ENSG00000111271,ACAD10,chr12,+,111710272,111710437,111709525,111709684,111715820,111715962,NaN,NaN,0.033138,"0.429,1.0","0.333,0.0",0.548,True
60530,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710353,111715820,111715962,NaN,NaN,1.000000,"0.429,1.0","1.0,1.0",-0.285,True
60531,SE,ENSG00000111271,ACAD10,chr12,+,111712497,111712657,111710272,111710437,111715820,111715962,NaN,NaN,1.000000,"1.0,0.846","1.0,1.0",-0.077,True